name: validation

env:
  node_version: 20
  pnpm_version: 8.15.1
  CI: true
  environment: dev

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - main
    types:
      - opened
      - synchronize
      - reopened
      - closed
jobs:
  validate:
    runs-on: ubuntu-latest
    name: Build Job on Dev
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0

      - name: 'Install NodeJs'
        uses: ./.github/actions/install
        with:
          node_version: ${{ env.node_version }}
          pnpm_version: ${{ env.pnpm_version }}
      - name: 'Install Go'
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.19.0'
      - run: go version

      - uses: nrwl/nx-set-shas@v3
      - run: git branch --track main origin/main

      - name: Nx - Unit Tests
        shell: bash
        run: |
          npx nx affected --target=test --parallel 1

      - name: Setup playwirght
        uses: microsoft/playwright-github-action@v1

      - name: Nx - e2e Tests
        env:
          CI: ${{ env.CI }}
        shell: bash
        run: |
          pnpm exec playwright install
          pnpm nx affected --target=e2e --parallel 1

      - name: Nx - Generate Test Report
        env:
          CI: ${{ env.CI }}
        shell: bash
        run: |
          pnpm nx run merge-js-reports:generate-js-reports
